version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
