version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    command: node server.js
